package com.example.myapplication.ui.theme

/**
 * Compose colors were generated by the initial template.
 * CleanSpace uses XML colors in res/values/colors.xml.
 */
object Colors {
    const val UNUSED = 0
}
