package com.example.myapplication.ui.theme

/**
 * Compose theme file was generated by the initial template.
 * CleanSpace uses XML + ViewBinding/DataBinding, so Compose is not used.
 */
object Theme {
    const val UNUSED = 0
}