package com.example.myapplication.ui.theme

/**
 * Compose typography was generated by the initial template.
 * CleanSpace uses XML text appearances/styles.
 */
object Type {
    const val UNUSED = 0
}
